import {Planet, Star, Spaceship} from './Entities'
import { Vector2D } from './Vector2D'

export const map = [
    new Star({ // Солнце
        name: "Sun",
        position: new Vector2D(0, 0),
        imageSrc: 'star',
        size: 200,
        mass: 1.64e17,
    }),
    new Planet({ // Земля
        name: "Earth",
        position: new Vector2D(-1000, 0),
        imageSrc: 'earth',
        size: 40,
        mass: 5e14,
        velocity: new Vector2D(0, 104.72),
        angVelocity: 0.3,
    }),
    new Planet({ // Меркурий
        name: "Mercury",
        position: new Vector2D(-387.7, 0),
        imageSrc: 'mercury',
        size: 20,
        mass: 5e13,
        velocity: new Vector2D(0, 166.86),
        angVelocity: 0.3,
    }),
    new Planet({ // Венера
        name: "Venus",
        position: new Vector2D(-721.93, 0),
        imageSrc: 'venus',
        size: 40,
        mass: 5e14,
        velocity: new Vector2D(0, 123.39),
        angVelocity: 0.3,
    }),
    new Planet({ // Марс
        name: "Mars",
        position: new Vector2D(-1524.06, 0),
        imageSrc: 'mars',
        size: 20,
        mass: 1e14,
        velocity: new Vector2D(0, 85.02),
        angVelocity: 0.3,
    }),
    new Spaceship({ // Корабль
        name: "Player",
        position: new Vector2D(-1035, 0),
        imageSrc: 'spacecraft',
        size: 8,
        mass: 1,
        maxThrust: 100,
        velocity: new Vector2D(0, 135),
    }),
    new Planet({ // Юпитер
        name: "Jupiter",
        position: new Vector2D(-5203.81, 0),
        imageSrc: 'jupiter',
        size: 60,
        mass: 5e15,
        velocity: new Vector2D(0, 45.96),
        angVelocity: 0.3,
    }),
    new Planet({ // Сатурн
        name: "Saturn",
        position: new Vector2D(-9582.55, 0),
        imageSrc: 'saturn',
        size: 60,
        mass: 5e15,
        velocity: new Vector2D(0, 34.04),
        angVelocity: 0.3,
    }),
    new Planet({ // Уран
        name: "Uranus",
        position: new Vector2D(-19229.39, 0),
        imageSrc: 'uranus',
        size: 40,
        mass: 5e15,
        velocity: new Vector2D(0, 23.91),
        angVelocity: 0.3,
    }),
    new Planet({ // Нептун
        name: "Neptune",
        position: new Vector2D(-30103.63, 0),
        imageSrc: 'neptune',
        size: 40,
        mass: 5e15,
        velocity: new Vector2D(0, 19.09),
        angVelocity: 0.3,
    }),
]